version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: update-dependency
  ignore:
  - dependency-name: "@vueuse/core"
    versions:
    - 4.0.10
    - 4.0.12
    - 4.1.0
    - 4.1.1
    - 4.2.1
    - 4.3.1
    - 4.3.4
    - 4.4.1
    - 4.7.0
  - dependency-name: rollup-plugin-dts
    versions:
    - 3.0.1
  - dependency-name: "@vue/composition-api"
    versions:
    - 1.0.0-rc.1
    - 1.0.0-rc.2
    - 1.0.0-rc.3
    - 1.0.0-rc.5
    - 1.0.0-rc.6
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.3
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.3
  - dependency-name: vue-demi
    versions:
    - 0.6.0
    - 0.7.1
    - 0.7.3
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.30.0
- package-ecosystem: npm
  directory: "/example"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: update-example-dependency
  ignore:
  - dependency-name: vite
    versions:
    - 2.0.0-beta.49
    - 2.0.0-beta.61
    - 2.0.0-beta.65
    - 2.0.0-beta.69
    - 2.0.1
    - 2.0.4
    - 2.0.5
    - 2.1.0
    - 2.1.2
    - 2.1.3
    - 2.1.5
  - dependency-name: "@vue/compiler-sfc"
    versions:
    - 3.0.5
    - 3.0.7
    - 3.0.9
  - dependency-name: vue
    versions:
    - 3.0.5
    - 3.0.7
    - 3.0.9
  - dependency-name: v-use-edit-image
    versions:
    - 0.6.4
